version: '3'
services:
  app-nginx:
    build:
      context: ./docker/development/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - app-php-fpm
    ports:
      - "8020:80"
  app-php-fpm:
    build:
      context: ./docker/development/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - app-postgres
  app-php-cli:
    build:
      context: ./docker/development/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - app-postgres
  app-postgres:
    image: postgres:11.2-alpine
    volumes:
      - app-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
      - "54322:5432"

volumes:
  app-postgres:
  composer:
